on: [push]
name: build
jobs:
  runhaskell:
    name: Run App
    runs-on: ubuntu-latest # or macOS-latest, or windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        with:
          cabal-version: '3.6'
      - run: cabal v2-run
