on: [push]
name: build
jobs:
  runhaskell:
    name: Type checking
    runs-on: macOS-latest # or ubuntu-latest, or windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@2
      - run: runhaskell Witnesses.hs
